import {
  home4BestSellerImg1,
  home4BestSellerImg2,
  home4BestSellerImg3,
  home4BestSellerImg4,
  home4JustInImg1,
  home4JustInImg2,
  home4JustInImg3,
  home4JustInImg4,
} from "@/images";

export const home4BestSellerData = [
  {
    _id: "1",
    name: "Freestyle Crew Racer leather jacket",
    description:
      "A stylish and comfortable loveseat sofa, perfect for modern living rooms.",
    price: 595.0,
    originalPrice: 1000.0,
    imageUrl: home4JustInImg4.src,
    rating: 5,
    isHotItem: true,
    category: "jacket",
  },
  {
    _id: "2",
    name: "1996 Retro Nuptse Jacket in Black",
    description:
      "A minimalist beige table lamp, ideal for bedside or desk lighting.",
    price: 149.99,
    imageUrl: home4JustInImg3.src,
    rating: 4,
    isNewItem: true,
    category: "winter",
  },
  {
    _id: "3",
    name: "Paradigm Chilliwack Black Label Jacket",
    description: "Greg Norman - Men's Shark Logo Golf Polo Shirt",
    price: 349.99,
    originalPrice: 449.99,
    imageUrl: home4JustInImg2.src,
    rating: 2.5,
    isNewItem: true,
    category: "winter",
  },
  {
    _id: "4",
    name: "96 Nuptse Dip Dye bomber Jacket",
    description:
      "A natural bamboo basket, great for stylish and eco-friendly storage.",
    price: 400.99,
    imageUrl: home4BestSellerImg1.src,
    isNewItem: true,
    isHotItem: true,
    rating: 4,
    category: "winter",
  },
  {
    _id: "5",
    name: "Oversized real leather harrington jacket in black",
    description:
      "A modern toaster with a premium finish, perfect for quick breakfasts.",
    price: 249.99,
    imageUrl: home4BestSellerImg2.src,
    rating: 5,
    isNewItem: true,
    category: "winter",
  },
  {
    _id: "6",
    name: "96 Nuptse Dip Dye Korea Puffers Jacket",
    description:
      "A stylish and comfortable loveseat sofa, perfect for modern living rooms.",
    price: 400.0,
    imageUrl: home4JustInImg1.src,
    rating: 5,
    isNewItem: true,
    category: "winter",
  },
  {
    _id: "7",
    name: "Paradigm Chilliwack coat Black Label",
    description:
      "A sleek table lamp that adds a warm and cozy ambiance to any space.",
    price: 1495.0,
    imageUrl: home4BestSellerImg3.src,
    rating: 2.5,
    isHotItem: true,
    isNewItem: true,
    category: "headphone",
  },
  {
    _id: "8",
    name: "Men's Torrentshell 3L Rain Jacket in Brown",
    description:
      "A minimalist beige table lamp, ideal for bedside or desk lighting.",
    price: 149.99,
    originalPrice: 199.99,
    imageUrl: home4BestSellerImg4.src,
    rating: 4,
    isHotItem: true,
    category: "winter",
  },
];
