import {
  home3FeaturedImg1,
  home3FeaturedImg2,
  home3FeaturedImg3,
  home3FeaturedImg4,
  home3FeaturedImg5,
} from "@/images";

export const home3FeaturedData = [
  {
    _id: "1",
    name: "Shark - Men's cabretta white golf glove ",
    description:
      "A stylish and comfortable loveseat sofa, perfect for modern living rooms.",
    price: 19.99,
    imageUrl: home3FeaturedImg1.src,
    rating: 5,
    isHotItem: true,
    category: "golf",
  },
  {
    _id: "2",
    name: "Greg Norman - Men's Shark Logo Golf Polo Shirt",
    description: "Greg Norman - Men's Shark Logo Golf Polo Shirt",
    price: 24.99,
    originalPrice: 40.0,
    imageUrl: home3FeaturedImg2.src,
    rating: 2.5,
    isHotItem: true,
    category: "golf",
  },
  {
    _id: "3",
    name: "G/FORE - Mens Left Glove Snow 2023",
    description:
      "A minimalist beige table lamp, ideal for bedside or desk lighting.",
    price: 30.0,
    imageUrl: home3FeaturedImg3.src,
    rating: 4,
    isNewItem: true,
    category: "golf",
  },
  {
    _id: "4",
    name: "Utility Rover-R Double Strap Bag All Black - 2023",
    description:
      "A natural bamboo basket, great for stylish and eco-friendly storage.",
    price: 209.99,
    imageUrl: home3FeaturedImg4.src,
    rating: 1,
    isNewItem: true,
    isHotItem: true,
    category: "golf",
  },
  {
    _id: "5",
    name: "Air Jordan 1 Low G Black/Black/Iron Grey - SS23",
    description:
      "A modern toaster with a premium finish, perfect for quick breakfasts.",
    price: 111.99,
    originalPrice: 200.0,
    imageUrl: home3FeaturedImg5.src,
    rating: 4.5,
    isNewItem: true,
    isHotItem: true,
    category: "shoes",
  },
  {
    _id: "6",
    name: "Shark - Men's cabretta white golf glove ",
    description:
      "A stylish and comfortable loveseat sofa, perfect for modern living rooms.",
    price: 19.99,
    imageUrl: home3FeaturedImg1.src,
    rating: 5,
    isHotItem: true,
    category: "golf",
  },
  {
    _id: "7",
    name: "Greg Norman - Men's Shark Logo Golf Polo Shirt",
    description: "Greg Norman - Men's Shark Logo Golf Polo Shirt",
    price: 24.99,
    originalPrice: 40.0,
    imageUrl: home3FeaturedImg2.src,
    rating: 2.5,
    isHotItem: true,
    category: "golf",
  },
  {
    _id: "8",
    name: "G/FORE - Mens Left Glove Snow 2023",
    description:
      "A minimalist beige table lamp, ideal for bedside or desk lighting.",
    price: 30.0,
    imageUrl: home3FeaturedImg3.src,
    rating: 4,
    isNewItem: true,
    category: "golf",
  },
  {
    _id: "9",
    name: "Utility Rover-R Double Strap Bag All Black - 2023",
    description:
      "A natural bamboo basket, great for stylish and eco-friendly storage.",
    price: 209.99,
    imageUrl: home3FeaturedImg4.src,
    rating: 1,
    isNewItem: true,
    isHotItem: true,
    category: "golf",
  },
  {
    _id: "10",
    name: "Air Jordan 1 Low G Black/Black/Iron Grey - SS23",
    description:
      "A modern toaster with a premium finish, perfect for quick breakfasts.",
    price: 111.99,
    originalPrice: 200.0,
    imageUrl: home3FeaturedImg5.src,
    rating: 4.5,
    isNewItem: true,
    isHotItem: true,
    category: "shoes",
  },
];
